version: '{branch}-{build}'
image: Ubuntu
build: off
environment:
  matrix:
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310
    - TOXENV: py311
install:
  - py -m pip install tox
test_script:
  - py -m tox
